apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}-sidecar
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: sidecar
spec:
  ports:
    - port: 10901
      protocol: TCP
      targetPort: grpc
      name: grpc
  selector:
    app: prometheus
    prometheus: {{ include "thanos.fullname" . }}-prometheus-operator-prometheus
  type: ClusterIP
  clusterIP: None
