apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  name: {{ include "thanos.fullname" . }}-sidecar
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: sidecar
spec:
  groups:
  - name: thanos-sidecar.rules
    rules:
    - alert: ThanosSidecarPrometheusDown
      expr: thanos_sidecar_prometheus_up{name="prometheus"} == 0
      for: 5m
      annotations:
        summary: Thanos Sidecar cannot connect to Prometheus
        impact: Prometheus configuration is not being refreshed
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
    - alert: ThanosSidecarBucketOperationsFailed
      expr: rate(thanos_objstore_bucket_operation_failures_total{name="prometheus"}[5m]) > 0
      for: 5m
      annotations:
        summary: Thanos Sidecar bucket operations are failing
        impact: We will lose metrics data if not fixed in 24h
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
    - alert: ThanosSidecarGrpcErrorRate
      expr: rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable",name="prometheus"}[5m]) > 0
      for: 5m
      annotations:
        summary: Thanos Sidecar is returning Internal/Unavailable errors
        impact: Prometheus queries are failing
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
