apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  name: {{ include "thanos.fullname" . }}-store
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: store
spec:
  groups:
  - name: thanos-store.rules
    rules:
    - alert: ThanosStoreGrpcErrorRate
      expr: rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable",app="thanos-store"}[5m]) > 0
      for: 5m
      annotations:
        summary: Thanos Store is returning Internal/Unavailable errors
        impact: Long Term Storage Prometheus queries are failing
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
    - alert: ThanosStoreBucketOperationsFailed
      expr: rate(thanos_objstore_bucket_operation_failures_total{app="thanos-store"}[5m]) > 0
      for: 5m
      annotations:
        summary: Thanos Store is failing to do bucket operations
        impact: Long Term Storage Prometheus queries are failing
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
